kind = "DojoContract"
class_hash = "0x4a2347f7617b571de3f9d7a46a08acc0633dfedafe603f72062ab9ba38de1b4"
original_class_hash = "0x4a2347f7617b571de3f9d7a46a08acc0633dfedafe603f72062ab9ba38de1b4"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_combat_contracts_combat_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::combat::contracts::combat_systems"
