kind = "DojoContract"
class_hash = "0x3863a92eee0c473c32e55a33f1947a3184529df9ada98166af3cf4b2cd61091"
original_class_hash = "0x3863a92eee0c473c32e55a33f1947a3184529df9ada98166af3cf4b2cd61091"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_realm_contracts_realm_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::realm::contracts::realm_systems"
