kind = "DojoContract"
class_hash = "0x409063a147c5d854d9765cdc93143831273e8f2f2ce043b4e25f4680e5c0c5a"
original_class_hash = "0x409063a147c5d854d9765cdc93143831273e8f2f2ce043b4e25f4680e5c0c5a"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_bank_contracts_bank_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::bank::contracts::bank_systems"
