kind = "DojoContract"
class_hash = "0x28c2de52b30358e7a77637884644a9e620a7b4d40681bc123a2b10bb9531cc8"
original_class_hash = "0x28c2de52b30358e7a77637884644a9e620a7b4d40681bc123a2b10bb9531cc8"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_map_contracts_map_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::map::contracts::map_systems"
